# ============================================================================
# V3.1 SRE Platform — Windows Deployment Script (PowerShell)
# ============================================================================
# Usage: .\scripts\deploy-windows.ps1 [-Env dev|prod] [-Local]
# ============================================================================

param(
    [ValidateSet("dev", "prod")]
    [string]$Env = "dev",
    [switch]$Local,
    [switch]$Help
)

$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectDir = Split-Path -Parent $ScriptDir

# ── Helper functions ─────────────────────────────────────────────────────
function Write-Info { Write-Host "[INFO] $args" -ForegroundColor Blue }
function Write-Ok { Write-Host "[OK] $args" -ForegroundColor Green }
function Write-Warn { Write-Host "[WARN] $args" -ForegroundColor Yellow }
function Write-Err { Write-Host "[ERROR] $args" -ForegroundColor Red }

function Show-Help {
    Write-Host @"
V3.1 SRE Platform — Windows Deployment Script

Usage:
    .\scripts\deploy-windows.ps1 [-Env dev|prod] [-Local]

Parameters:
    -Env    Environment: dev (default) or prod
    -Local  Deploy locally without Docker
    -Help   Show this help

Examples:
    .\scripts\deploy-windows.ps1                    # Deploy dev with Docker
    .\scripts\deploy-windows.ps1 -Env prod          # Deploy production
    .\scripts\deploy-windows.ps1 -Local             # Deploy locally
"@
}

# ── Check prerequisites ──────────────────────────────────────────────────
function Test-Prerequisites {
    Write-Info "Checking prerequisites..."

    # Check Docker
    try {
        $dockerVersion = docker --version 2>$null
        Write-Ok "Docker found: $dockerVersion"
    } catch {
        Write-Err "Docker is not installed. Please install Docker Desktop."
        Write-Info "Download: https://www.docker.com/products/docker-desktop/"
        exit 1
    }

    # Check Docker Compose
    try {
        docker compose version 2>$null | Out-Null
        Write-Ok "Docker Compose available"
    } catch {
        Write-Err "Docker Compose is not available."
        exit 1
    }

    # Check Python (for local deployment)
    if ($Local) {
        try {
            $pythonVersion = python --version 2>&1
            Write-Ok "Python found: $pythonVersion"
        } catch {
            Write-Warn "Python not found. Install Python 3.12+ for local deployment."
        }

        try {
            $nodeVersion = node --version 2>&1
            Write-Ok "Node.js found: $nodeVersion"
        } catch {
            Write-Warn "Node.js not found. Install Node.js 20+ for local deployment."
        }
    }
}

# ── Create environment file ──────────────────────────────────────────────
function New-EnvFile {
    Write-Info "Setting up environment configuration..."

    $envPath = Join-Path $ProjectDir ".env"

    if (Test-Path $envPath) {
        Write-Warn ".env file already exists, skipping"
        return
    }

    $envContent = @"
# V3.1 SRE Platform Configuration
# Generated by deploy script

# Application
APP_NAME=Engineer Assist
APP_VERSION=3.1.0
APP_ENV=development
APP_DEBUG=true

# Database
DATABASE_URL=postgresql+asyncpg://v31:v31_dev_password@postgres:5432/v31_sre
DB_POOL_SIZE=20
DB_MAX_OVERFLOW=10

# Redis
REDIS_URL=redis://redis:6379/0

# JWT (CHANGE IN PRODUCTION!)
JWT_SECRET_KEY=dev-secret-key-change-in-production

# CORS
CORS_ORIGINS=http://localhost:3000,http://localhost:5173

# Logging
LOG_LEVEL=DEBUG
LOG_FORMAT=console

# Auth
DEV_DEFAULT_USER=dev-user
"@

    $envContent | Out-File -FilePath $envPath -Encoding UTF8
    Write-Ok "Created .env file"
}

# ── Setup production environment ─────────────────────────────────────────
function New-ProdEnv {
    Write-Info "Setting up production environment..."

    # Generate secrets
    $jwtSecret = -join ((1..128) | ForEach-Object { '{0:x}' -f (Get-Random -Max 16) })
    $dbPassword = -join ((1..32) | ForEach-Object { [char](Get-Random -Min 33 -Max 126) })

    # Create secrets directory
    $secretsDir = Join-Path $ProjectDir "secrets"
    if (!(Test-Path $secretsDir)) {
        New-Item -ItemType Directory -Path $secretsDir | Out-Null
    }

    $dbPassword | Out-File -FilePath (Join-Path $secretsDir "db_password.txt") -Encoding UTF8
    $jwtSecret | Out-File -FilePath (Join-Path $secretsDir "jwt_secret.txt") -Encoding UTF8

    # Create production .env
    $envContent = @"
# V3.1 SRE Platform — Production Configuration
APP_NAME=Engineer Assist
APP_VERSION=3.1.0
APP_ENV=production
APP_DEBUG=false

DATABASE_URL=postgresql+asyncpg://sre_app:${dbPassword}@postgres:5432/v31_sre
DB_POOL_SIZE=20
DB_MAX_OVERFLOW=10

REDIS_URL=redis://redis:6379/0

JWT_SECRET_KEY=${jwtSecret}
CORS_ORIGINS=https://sre.example.com

LOG_LEVEL=INFO
LOG_FORMAT=json
"@

    $envContent | Out-File -FilePath (Join-Path $ProjectDir ".env") -Encoding UTF8
    Write-Ok "Production environment configured"
    Write-Warn "Secrets saved to secrets/ directory — KEEP SECURE!"
}

# ── Deploy with Docker ───────────────────────────────────────────────────
function Start-DockerDeployment {
    Write-Info "Deploying with Docker Compose (${Env})..."

    Push-Location $ProjectDir

    try {
        if ($Env -eq "prod") {
            # Production deployment
            docker compose -f docker-compose.prod.yml build
            docker compose -f docker-compose.prod.yml up -d

            Write-Info "Waiting for services to start..."
            Start-Sleep -Seconds 10

            Write-Info "Running database migrations..."
            docker compose -f docker-compose.prod.yml exec backend alembic upgrade head

            Write-Ok "Production deployment complete"
            Write-Info "Access: https://sre.example.com"
        } else {
            # Development deployment
            docker compose up -d

            Write-Info "Waiting for services to start..."
            Start-Sleep -Seconds 10

            Write-Ok "Development deployment complete"
            Write-Info "Frontend: http://localhost:3000"
            Write-Info "Backend: http://localhost:8688"
            Write-Info "API Docs: http://localhost:8688/docs"
        }
    } finally {
        Pop-Location
    }
}

# ── Deploy locally ───────────────────────────────────────────────────────
function Start-LocalDeployment {
    Write-Info "Deploying locally..."

    Push-Location $ProjectDir

    try {
        # Start infrastructure
        docker compose up -d postgres redis

        # Setup backend
        Write-Info "Setting up backend..."
        Set-Location (Join-Path $ProjectDir "backend")
        python -m venv .venv
        & .\.venv\Scripts\Activate.ps1
        pip install -r requirements.txt

        # Run migrations
        Write-Info "Running migrations..."
        alembic upgrade head

        # Start backend
        Write-Info "Starting backend..."
        $backendJob = Start-Job -ScriptBlock {
            Set-Location $using:ProjectDir\backend
            & .\.venv\Scripts\Activate.ps1
            uvicorn app.main:app --reload --host 0.0.0.0 --port 8688
        }

        # Setup frontend
        Write-Info "Setting up frontend..."
        Set-Location (Join-Path $ProjectDir "frontend")
        npm install

        # Start frontend
        Write-Info "Starting frontend..."
        $frontendJob = Start-Job -ScriptBlock {
            Set-Location $using:ProjectDir\frontend
            npm run dev
        }

        Write-Ok "Local deployment complete"
        Write-Info "Frontend: http://localhost:3000"
        Write-Info "Backend: http://localhost:8688"
        Write-Info "Press Ctrl+C to stop"

        # Wait for jobs
        try {
            Wait-Job $backendJob, $frontendJob
        } finally {
            Stop-Job $backendJob, $frontendJob
            Remove-Job $backendJob, $frontendJob -Force
        }
    } finally {
        Pop-Location
    }
}

# ── Verify deployment ────────────────────────────────────────────────────
function Test-Deployment {
    Write-Info "Verifying deployment..."

    try {
        $health = Invoke-RestMethod -Uri "http://localhost:8688/health" -ErrorAction Stop
        if ($health.status -eq "healthy" -or $health.status -eq "ok") {
            Write-Ok "Backend health check passed"
        } else {
            Write-Err "Backend health check failed"
            return $false
        }
    } catch {
        Write-Err "Backend health check failed: $_"
        return $false
    }

    try {
        $frontend = Invoke-WebRequest -Uri "http://localhost:3000" -UseBasicParsing -ErrorAction Stop
        if ($frontend.Content -match "SRE") {
            Write-Ok "Frontend is accessible"
        } else {
            Write-Warn "Frontend may not be ready yet"
        }
    } catch {
        Write-Warn "Frontend check failed: $_"
    }

    Write-Ok "Deployment verification complete"
    return $true
}

# ── Main ─────────────────────────────────────────────────────────────────
function Main {
    if ($Help) {
        Show-Help
        return
    }

    Write-Host "=========================================="
    Write-Host " V3.1 SRE Platform — Windows Deployment"
    Write-Host "=========================================="
    Write-Host ""

    Test-Prerequisites

    if ($Local) {
        New-EnvFile
        Start-LocalDeployment
    } else {
        if ($Env -eq "prod") {
            New-ProdEnv
        } else {
            New-EnvFile
        }
        Start-DockerDeployment
        Test-Deployment
    }

    Write-Host ""
    Write-Ok "Deployment complete!"
}

Main
