#!/bin/bash
# ============================================================================
# V3.1 SRE Platform — Linux Deployment Script
# ============================================================================
# Usage: ./scripts/deploy-linux.sh [dev|prod]
# ============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV="${1:-dev}"

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# ── Check prerequisites ──────────────────────────────────────────────────
check_prerequisites() {
    log_info "Checking prerequisites..."

    # Check Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed. Please install Docker first."
        log_info "Install: https://docs.docker.com/engine/install/"
        exit 1
    fi

    # Check Docker Compose
    if ! docker compose version &> /dev/null; then
        log_error "Docker Compose is not available."
        exit 1
    fi

    # Check Python (for local development)
    if [ "$ENV" = "dev" ]; then
        if ! command -v python3 &> /dev/null; then
            log_warn "Python3 not found. Using Docker only."
        fi

        if ! command -v node &> /dev/null; then
            log_warn "Node.js not found. Using Docker only."
        fi
    fi

    log_success "Prerequisites check passed"
}

# ── Create environment file ──────────────────────────────────────────────
setup_env() {
    log_info "Setting up environment configuration..."

    if [ ! -f "$PROJECT_DIR/.env" ]; then
        cat > "$PROJECT_DIR/.env" << 'EOF'
# V3.1 SRE Platform Configuration
# Generated by deploy script

# Application
APP_NAME=Engineer Assist
APP_VERSION=3.1.0
APP_ENV=development
APP_DEBUG=true

# Database
DATABASE_URL=postgresql+asyncpg://v31:v31_dev_password@postgres:5432/v31_sre
DB_POOL_SIZE=20
DB_MAX_OVERFLOW=10

# Redis
REDIS_URL=redis://redis:6379/0

# JWT (CHANGE IN PRODUCTION!)
JWT_SECRET_KEY=dev-secret-key-change-in-production

# CORS
CORS_ORIGINS=http://localhost:3000,http://localhost:5173

# Logging
LOG_LEVEL=DEBUG
LOG_FORMAT=console

# Auth
DEV_DEFAULT_USER=dev-user
EOF
        log_success "Created .env file"
    else
        log_warn ".env file already exists, skipping"
    fi
}

# ── Setup production environment ─────────────────────────────────────────
setup_prod_env() {
    log_info "Setting up production environment..."

    # Generate secrets
    JWT_SECRET=$(openssl rand -hex 64)
    DB_PASSWORD=$(openssl rand -base64 32)

    # Create secrets directory
    mkdir -p "$PROJECT_DIR/secrets"
    echo "$DB_PASSWORD" > "$PROJECT_DIR/secrets/db_password.txt"
    echo "$JWT_SECRET" > "$PROJECT_DIR/secrets/jwt_secret.txt"
    chmod 600 "$PROJECT_DIR/secrets"/*.txt

    # Create production .env
    cat > "$PROJECT_DIR/.env" << EOF
# V3.1 SRE Platform — Production Configuration
APP_NAME=Engineer Assist
APP_VERSION=3.1.0
APP_ENV=production
APP_DEBUG=false

DATABASE_URL=postgresql+asyncpg://sre_app:${DB_PASSWORD}@postgres:5432/v31_sre
DB_POOL_SIZE=20
DB_MAX_OVERFLOW=10

REDIS_URL=redis://redis:6379/0

JWT_SECRET_KEY=${JWT_SECRET}
CORS_ORIGINS=https://sre.example.com

LOG_LEVEL=INFO
LOG_FORMAT=json
EOF

    log_success "Production environment configured"
    log_warn "Secrets saved to secrets/ directory — KEEP SECURE!"
}

# ── Deploy with Docker ───────────────────────────────────────────────────
deploy_docker() {
    log_info "Deploying with Docker Compose (${ENV})..."

    cd "$PROJECT_DIR"

    if [ "$ENV" = "prod" ]; then
        # Production deployment
        docker compose -f docker-compose.prod.yml build
        docker compose -f docker-compose.prod.yml up -d

        # Wait for services
        log_info "Waiting for services to start..."
        sleep 10

        # Run migrations
        log_info "Running database migrations..."
        docker compose -f docker-compose.prod.yml exec backend alembic upgrade head

        log_success "Production deployment complete"
        log_info "Access: https://sre.example.com"
    else
        # Development deployment
        docker compose up -d

        # Wait for services
        log_info "Waiting for services to start..."
        sleep 10

        log_success "Development deployment complete"
        log_info "Frontend: http://localhost:3000"
        log_info "Backend: http://localhost:8688"
        log_info "API Docs: http://localhost:8688/docs"
    fi
}

# ── Deploy locally ───────────────────────────────────────────────────────
deploy_local() {
    log_info "Deploying locally..."

    cd "$PROJECT_DIR"

    # Start infrastructure
    docker compose up -d postgres redis

    # Setup backend
    log_info "Setting up backend..."
    cd "$PROJECT_DIR/backend"
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt

    # Run migrations
    log_info "Running migrations..."
    alembic upgrade head

    # Seed data
    log_info "Seeding test data..."
    cd "$PROJECT_DIR/db/seeds"
    python3 generate_test_data.py --output /tmp/seed.sql
    docker exec -i v31-postgres psql -U v31 -d v31_sre < /tmp/seed.sql

    # Start backend
    log_info "Starting backend..."
    cd "$PROJECT_DIR/backend"
    uvicorn app.main:app --reload --host 0.0.0.0 --port 8688 &
    BACKEND_PID=$!

    # Setup frontend
    log_info "Setting up frontend..."
    cd "$PROJECT_DIR/frontend"
    npm install
    npm run dev &
    FRONTEND_PID=$!

    log_success "Local deployment complete"
    log_info "Frontend: http://localhost:3000"
    log_info "Backend: http://localhost:8688"
    log_info "Press Ctrl+C to stop"

    # Wait for interrupt
    trap "kill $BACKEND_PID $FRONTEND_PID 2>/dev/null; exit" SIGINT SIGTERM
    wait
}

# ── Verify deployment ────────────────────────────────────────────────────
verify_deployment() {
    log_info "Verifying deployment..."

    # Check health
    if curl -s http://localhost:8688/health | grep -q "healthy"; then
        log_success "Backend health check passed"
    else
        log_error "Backend health check failed"
        return 1
    fi

    # Check frontend
    if curl -s http://localhost:3000 | grep -q "SRE"; then
        log_success "Frontend is accessible"
    else
        log_warn "Frontend may not be ready yet"
    fi

    log_success "Deployment verification complete"
}

# ── Main ─────────────────────────────────────────────────────────────────
main() {
    echo "=========================================="
    echo " V3.1 SRE Platform — Linux Deployment"
    echo "=========================================="
    echo ""

    check_prerequisites

    case "$ENV" in
        dev)
            setup_env
            deploy_docker
            verify_deployment
            ;;
        prod)
            setup_prod_env
            deploy_docker
            verify_deployment
            ;;
        local)
            setup_env
            deploy_local
            ;;
        *)
            log_error "Unknown environment: $ENV"
            echo "Usage: $0 [dev|prod|local]"
            exit 1
            ;;
    esac

    echo ""
    log_success "Deployment complete!"
}

main "$@"
