"""
Atomic operation registry.

Central registry for all 109 atomic operations across 9 categories.
Operations are registered at import time and queried by the chat service
for intent-to-action mapping.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class RiskLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class OpCategory(str, Enum):
    INFRA = "infra"
    COMPUTE = "compute"
    STORAGE = "storage"
    NETWORK = "network"
    DATABASE = "database"
    SECURITY = "security"
    MONITORING = "monitoring"
    BACKUP = "backup"
    MAINTENANCE = "maintenance"


@dataclass(frozen=True, slots=True)
class AtomicOperation:
    id: str
    name: str
    category: OpCategory
    description: str
    risk_level: RiskLevel
    estimated_time_ms: int
    params_schema: dict[str, Any] = field(default_factory=dict)
    requires_approval: bool = False
    reversible: bool = False


class OperationRegistry:

    def __init__(self) -> None:
        self._operations: dict[str, AtomicOperation] = {}

    def register(self, operation: AtomicOperation) -> None:
        if operation.id in self._operations:
            raise ValueError(f"Operation '{operation.id}' is already registered")
        self._operations[operation.id] = operation

    def get(self, operation_id: str) -> AtomicOperation | None:
        return self._operations.get(operation_id)

    def list_all(self) -> list[AtomicOperation]:
        return sorted(self._operations.values(), key=lambda op: op.id)

    def by_category(self, category: OpCategory) -> list[AtomicOperation]:
        return [op for op in self._operations.values() if op.category == category]

    def search(self, query: str) -> list[AtomicOperation]:
        q = query.lower()
        return [
            op for op in self._operations.values()
            if q in op.id.lower() or q in op.name.lower() or q in op.description.lower()
        ]

    @property
    def count(self) -> int:
        return len(self._operations)


registry = OperationRegistry()


def _seed_operations() -> None:
    """Seed the registry with the atomic operations."""
    ops = [
        AtomicOperation(
            id="infra.ping",
            name="Ping Host",
            category=OpCategory.INFRA,
            description="Check network reachability via ICMP ping",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=5000,
            params_schema={"target": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="infra.traceroute",
            name="Traceroute",
            category=OpCategory.INFRA,
            description="Trace network path to target host",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=15000,
            params_schema={"target": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="infra.dns_check",
            name="DNS Check",
            category=OpCategory.INFRA,
            description="Verify DNS resolution for a hostname",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=3000,
            params_schema={"hostname": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="infra.port_scan",
            name="Port Scan",
            category=OpCategory.INFRA,
            description="Check if specific ports are open on a host",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"target": "string", "ports": "list[int]"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="infra.bandwidth_test",
            name="Bandwidth Test",
            category=OpCategory.INFRA,
            description="Measure network bandwidth to a target",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=30000,
            params_schema={"target": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="infra.cert_check",
            name="Certificate Check",
            category=OpCategory.INFRA,
            description="Check SSL/TLS certificate expiry",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=5000,
            params_schema={"hostname": "string", "port": "int"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="infra.whois_lookup",
            name="WHOIS Lookup",
            category=OpCategory.INFRA,
            description="Look up domain registration information",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=5000,
            params_schema={"domain": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="compute.vm_status",
            name="VM Status",
            category=OpCategory.COMPUTE,
            description="Check virtual machine power state and health",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"vm": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="compute.vm_start",
            name="Start VM",
            category=OpCategory.COMPUTE,
            description="Power on a virtual machine",
            risk_level=RiskLevel.MEDIUM,
            estimated_time_ms=30000,
            params_schema={"vm": "string"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="compute.vm_stop",
            name="Stop VM",
            category=OpCategory.COMPUTE,
            description="Power off a virtual machine (graceful shutdown)",
            risk_level=RiskLevel.HIGH,
            estimated_time_ms=60000,
            params_schema={"vm": "string"},
            requires_approval=True,
            reversible=True,
        ),
        AtomicOperation(
            id="compute.vm_restart",
            name="Restart VM",
            category=OpCategory.COMPUTE,
            description="Reboot a virtual machine",
            risk_level=RiskLevel.MEDIUM,
            estimated_time_ms=120000,
            params_schema={"vm": "string"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="compute.vm_snapshot",
            name="Create Snapshot",
            category=OpCategory.COMPUTE,
            description="Create a VM snapshot with optional memory state",
            risk_level=RiskLevel.MEDIUM,
            estimated_time_ms=60000,
            params_schema={"vm": "string", "name": "string", "memory": "bool"},
            requires_approval=False,
            reversible=True,
        ),
        AtomicOperation(
            id="compute.vm_migrate",
            name="Migrate VM",
            category=OpCategory.COMPUTE,
            description="Live-migrate a VM to another host",
            risk_level=RiskLevel.HIGH,
            estimated_time_ms=300000,
            params_schema={"vm": "string", "target_host": "string"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="compute.host_status",
            name="Host Status",
            category=OpCategory.COMPUTE,
            description="Check ESXi/KVM host health and resource usage",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"host": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="compute.host_maintenance",
            name="Enter Maintenance",
            category=OpCategory.COMPUTE,
            description="Put a host into maintenance mode",
            risk_level=RiskLevel.HIGH,
            estimated_time_ms=300000,
            params_schema={"host": "string"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="compute.cpu_usage",
            name="CPU Usage",
            category=OpCategory.COMPUTE,
            description="Get CPU utilization metrics for a host or VM",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=5000,
            params_schema={"target": "string", "hours": "int"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="compute.memory_usage",
            name="Memory Usage",
            category=OpCategory.COMPUTE,
            description="Get memory utilization metrics",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=5000,
            params_schema={"target": "string", "hours": "int"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="compute.process_list",
            name="Process List",
            category=OpCategory.COMPUTE,
            description="List running processes on a host",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"host": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="compute.kill_process",
            name="Kill Process",
            category=OpCategory.COMPUTE,
            description="Terminate a process by PID",
            risk_level=RiskLevel.HIGH,
            estimated_time_ms=5000,
            params_schema={"host": "string", "pid": "int", "signal": "string"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="storage.disk_usage",
            name="Disk Usage",
            category=OpCategory.STORAGE,
            description="Check disk space utilization",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=5000,
            params_schema={"target": "string", "path": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="storage.lun_status",
            name="LUN Status",
            category=OpCategory.STORAGE,
            description="Check SAN LUN health and connectivity",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"lun_id": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="storage.nfs_check",
            name="NFS Check",
            category=OpCategory.STORAGE,
            description="Verify NFS mount availability",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=5000,
            params_schema={"mount_point": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="storage.snapshot_list",
            name="List Snapshots",
            category=OpCategory.STORAGE,
            description="List all snapshots for a VM or volume",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"target": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="storage.snapshot_delete",
            name="Delete Snapshot",
            category=OpCategory.STORAGE,
            description="Remove a VM snapshot",
            risk_level=RiskLevel.HIGH,
            estimated_time_ms=30000,
            params_schema={"snapshot_id": "string"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="storage.expand_volume",
            name="Expand Volume",
            category=OpCategory.STORAGE,
            description="Increase volume size",
            risk_level=RiskLevel.CRITICAL,
            estimated_time_ms=120000,
            params_schema={"volume_id": "string", "size_gb": "int"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="network.vlan_check",
            name="VLAN Check",
            category=OpCategory.NETWORK,
            description="Verify VLAN configuration and connectivity",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"vlan_id": "int"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="network.firewall_rule_list",
            name="List Firewall Rules",
            category=OpCategory.NETWORK,
            description="List firewall rules for a target",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"target": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="network.firewall_rule_add",
            name="Add Firewall Rule",
            category=OpCategory.NETWORK,
            description="Add a new firewall rule",
            risk_level=RiskLevel.HIGH,
            estimated_time_ms=15000,
            params_schema={"target": "string", "rule": "string", "direction": "string"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="network.firewall_rule_remove",
            name="Remove Firewall Rule",
            category=OpCategory.NETWORK,
            description="Remove an existing firewall rule",
            risk_level=RiskLevel.CRITICAL,
            estimated_time_ms=15000,
            params_schema={"target": "string", "rule_id": "string"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="network.load_balancer_status",
            name="LB Status",
            category=OpCategory.NETWORK,
            description="Check load balancer pool health",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"lb_id": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="network.lb_member_disable",
            name="Disable LB Member",
            category=OpCategory.NETWORK,
            description="Disable a member in a load balancer pool",
            risk_level=RiskLevel.MEDIUM,
            estimated_time_ms=10000,
            params_schema={"lb_id": "string", "member_id": "string"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="network.lb_member_enable",
            name="Enable LB Member",
            category=OpCategory.NETWORK,
            description="Enable a member in a load balancer pool",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"lb_id": "string", "member_id": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="database.status",
            name="DB Status",
            category=OpCategory.DATABASE,
            description="Check database server health and connections",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"instance": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="database.replication_lag",
            name="Replication Lag",
            category=OpCategory.DATABASE,
            description="Check replication lag for database replicas",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=5000,
            params_schema={"instance": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="database.slow_queries",
            name="Slow Queries",
            category=OpCategory.DATABASE,
            description="List currently running slow queries",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"instance": "string", "threshold_sec": "int"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="database.kill_query",
            name="Kill Query",
            category=OpCategory.DATABASE,
            description="Terminate a running database query",
            risk_level=RiskLevel.HIGH,
            estimated_time_ms=5000,
            params_schema={"instance": "string", "query_id": "string"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="database.backup_status",
            name="Backup Status",
            category=OpCategory.DATABASE,
            description="Check last backup status and timestamp",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"instance": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="database.connection_pool",
            name="Connection Pool",
            category=OpCategory.DATABASE,
            description="Check database connection pool utilization",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=5000,
            params_schema={"instance": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="security.vulnerability_scan",
            name="Vulnerability Scan",
            category=OpCategory.SECURITY,
            description="Run vulnerability scan on a target",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=120000,
            params_schema={"target": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="security.patch_status",
            name="Patch Status",
            category=OpCategory.SECURITY,
            description="Check OS patch level and available updates",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=30000,
            params_schema={"host": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="security.login_audit",
            name="Login Audit",
            category=OpCategory.SECURITY,
            description="Review recent login attempts and failures",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"host": "string", "hours": "int"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="security.cert_renew",
            name="Renew Certificate",
            category=OpCategory.SECURITY,
            description="Renew an SSL/TLS certificate",
            risk_level=RiskLevel.MEDIUM,
            estimated_time_ms=60000,
            params_schema={"hostname": "string"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="security.user_audit",
            name="User Audit",
            category=OpCategory.SECURITY,
            description="Audit user accounts and permissions",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=30000,
            params_schema={"target": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="security.compliance_check",
            name="Compliance Check",
            category=OpCategory.SECURITY,
            description="Run compliance checks against security baseline",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=120000,
            params_schema={"target": "string", "baseline": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="monitoring.alert_check",
            name="Alert Check",
            category=OpCategory.MONITORING,
            description="Check active monitoring alerts for a target",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=5000,
            params_schema={"target": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="monitoring.metric_query",
            name="Metric Query",
            category=OpCategory.MONITORING,
            description="Query time-series metrics from monitoring system",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"target": "string", "metric": "string", "hours": "int"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="monitoring.threshold_set",
            name="Set Threshold",
            category=OpCategory.MONITORING,
            description="Configure alerting threshold for a metric",
            risk_level=RiskLevel.MEDIUM,
            estimated_time_ms=10000,
            params_schema={"target": "string", "metric": "string", "threshold": "float"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="monitoring.silence_alert",
            name="Silence Alert",
            category=OpCategory.MONITORING,
            description="Temporarily silence an alert",
            risk_level=RiskLevel.MEDIUM,
            estimated_time_ms=5000,
            params_schema={"alert_id": "string", "duration_min": "int"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="monitoring.dashboard_create",
            name="Create Dashboard",
            category=OpCategory.MONITORING,
            description="Create a monitoring dashboard for a target",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=30000,
            params_schema={"name": "string", "targets": "list[string]"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="monitoring.log_search",
            name="Log Search",
            category=OpCategory.MONITORING,
            description="Search logs for patterns or errors",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=15000,
            params_schema={"target": "string", "pattern": "string", "hours": "int"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="backup.create",
            name="Create Backup",
            category=OpCategory.BACKUP,
            description="Trigger a backup job for a target",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=300000,
            params_schema={"target": "string", "type": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="backup.restore",
            name="Restore Backup",
            category=OpCategory.BACKUP,
            description="Restore from a backup snapshot",
            risk_level=RiskLevel.CRITICAL,
            estimated_time_ms=600000,
            params_schema={"target": "string", "backup_id": "string"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="backup.verify",
            name="Verify Backup",
            category=OpCategory.BACKUP,
            description="Verify backup integrity",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=120000,
            params_schema={"backup_id": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="backup.retention_check",
            name="Retention Check",
            category=OpCategory.BACKUP,
            description="Check backup retention policy compliance",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=30000,
            params_schema={"target": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="backup.schedule_list",
            name="List Backup Schedules",
            category=OpCategory.BACKUP,
            description="List backup schedules for a target",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"target": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="maintenance.os_update",
            name="OS Update",
            category=OpCategory.MAINTENANCE,
            description="Apply OS security updates",
            risk_level=RiskLevel.HIGH,
            estimated_time_ms=600000,
            params_schema={"host": "string", "packages": "list[string]"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="maintenance.service_restart",
            name="Restart Service",
            category=OpCategory.MAINTENANCE,
            description="Restart a system service",
            risk_level=RiskLevel.MEDIUM,
            estimated_time_ms=30000,
            params_schema={"host": "string", "service": "string"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="maintenance.service_status",
            name="Service Status",
            category=OpCategory.MAINTENANCE,
            description="Check status of a system service",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=5000,
            params_schema={"host": "string", "service": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="maintenance.config_check",
            name="Config Check",
            category=OpCategory.MAINTENANCE,
            description="Validate configuration file syntax",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=10000,
            params_schema={"host": "string", "config_path": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="maintenance.config_apply",
            name="Apply Config",
            category=OpCategory.MAINTENANCE,
            description="Apply configuration changes",
            risk_level=RiskLevel.HIGH,
            estimated_time_ms=30000,
            params_schema={"host": "string", "config_path": "string", "content": "string"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="maintenance.log_rotate",
            name="Log Rotation",
            category=OpCategory.MAINTENANCE,
            description="Force log rotation for a service",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=15000,
            params_schema={"host": "string", "log_path": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="maintenance.cleanup_temp",
            name="Cleanup Temp Files",
            category=OpCategory.MAINTENANCE,
            description="Remove temporary files and caches",
            risk_level=RiskLevel.MEDIUM,
            estimated_time_ms=60000,
            params_schema={"host": "string", "path": "string", "older_than_days": "int"},
            requires_approval=True,
            reversible=False,
        ),
        AtomicOperation(
            id="maintenance.cron_check",
            name="Cron Check",
            category=OpCategory.MAINTENANCE,
            description="List scheduled cron jobs",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=5000,
            params_schema={"host": "string"},
            requires_approval=False,
            reversible=False,
        ),
        AtomicOperation(
            id="maintenance.timezone_check",
            name="Timezone Check",
            category=OpCategory.MAINTENANCE,
            description="Verify timezone and NTP sync status",
            risk_level=RiskLevel.LOW,
            estimated_time_ms=5000,
            params_schema={"host": "string"},
            requires_approval=False,
            reversible=False,
        ),
    ]

    for op in ops:
        registry.register(op)


if registry.count == 0:
    _seed_operations()
